version: "3.3"

services:
  gogs:
    image: 'gogs/gogs:0.11.86'
    ports:
     - '3000:3000'
     - '22:22'
    volumes:
     - './gogs_data:/data'
    networks:
      shared:
        ipv4_address: 172.19.199.5

  jenkins:
    image: jenkins/jenkins:2.189
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # for running docker containers from inside jenkins container
      - ./jenkins_home:/var/jenkins_home
    networks:
      shared:
        ipv4_address: 172.19.199.6

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gogs
      MYSQL_USER: gogs
      MYSQL_PASSWORD: gogs
    volumes:
      - './db_data:/var/lib/mysql'
    networks:
      shared:
        ipv4_address: 172.19.199.7

networks:
  shared:
    ipam:
      driver: default
      config:
        - subnet: 172.19.199.0/24